Repository quanduongduc/se2022-15.3, pull requests merged in 2023-02, with the labels that each got.

#37 fix-cannot-connect-database-on-deploy
  backend/.env
  docker-compose.production.yml
  docker-compose.yml
Labels: done

#39 Nginx-cannot-forward-headers
  nginx/default.conf
Labels: done

#40 Backend
  backend/readme.md
  backend/src/controllers/artist.controller.ts
Labels: bug

#42 fix-cannot-upload-file-have-size-large
  nginx/default.conf
Labels: done

#43 add check condition in register page and fix error white page when login with new account and remove code not need
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/tsx/Home.tsx
  frontend/src/context/PlaylistContextProvider.tsx
  frontend/src/pages/register/RegisterPage.tsx
  frontend/src/pages/register/register.css
Labels: done

#53 Sửa firstName and lastname không nhận dấu tiếng việt và hạn chế ký tự đặc biệt ở tên tài khoản . _
  backend/src/middlewares/validate.midleware.ts
  backend/src/test/helpers.ts
  backend/src/test/integration/route/auth.spec.ts
  backend/src/test/integration/route/user.spec.ts
  frontend/package-lock.json
  frontend/src/pages/login/LoginPage.tsx
  frontend/src/pages/register/RegisterPage.tsx
Labels: done

#54 fix-syntax
  frontend/src/pages/login/LoginPage.tsx
  frontend/src/pages/register/RegisterPage.tsx
Labels: bug

#57 fix-loop-list-favorite-track
  frontend/src/components/tsx/PlayingBar.tsx
Labels: done

#59 edit-size-image-song-in-playingbar
  frontend/src/components/css/playingbar.css
  frontend/src/components/css/playlistView.css
  frontend/src/components/tsx/Favorite.tsx
  frontend/src/components/tsx/PlayingBar.tsx
  frontend/src/components/tsx/PlaylistCreate.tsx
  frontend/src/components/tsx/PlaylistView.tsx
  frontend/src/components/tsx/Tracks.tsx
Labels: done

#60 Lỗi khoảng cách merge lại
  frontend/src/components/tsx/Favorite.tsx
  frontend/src/components/tsx/Tracks.tsx
Labels: bug, done

#63 62 hide env file
  .env
  .github/workflows/deploy.yml
  .gitignore
  backend/.env
  backend/example.env
  dev.env
  example.env
Labels: enhancement, done

#64 Documentation
  README.md
Labels: documentation
